Run if in one line

diff --git a/.github/workflows/Publish_to_Github_Pages.yml b/.github/workflows/Publish_to_Github_Pages.yml
--- a/.github/workflows/Publish_to_Github_Pages.yml
+++ b/.github/workflows/Publish_to_Github_Pages.yml
@@ -23,10 +23,7 @@ jobs:
         #1GB = 1073741824 bytes
         run: |
           SIZE=$(du -s -B 1 app_web/dist/ | cut -f 1)
-          if [[ $SIZE -gt 1073741824]]; then
-             echo 'dist folder exceeds limit of 1GB! Aborting'
-             exit 1
-          fi
+          if [[ $SIZE -gt 1073741824 ]]; then echo 'dist folder exceeds limit of 1GB! Aborting'; exit 1; fi
 
       - name: Deploy
         uses: JamesIves/github-pages-deploy-action@4.1.0
