Do not overwrite physics demo

diff --git a/.github/workflows/Publish_to_Github_Pages.yml b/.github/workflows/Publish_to_Github_Pages.yml
--- a/.github/workflows/Publish_to_Github_Pages.yml
+++ b/.github/workflows/Publish_to_Github_Pages.yml
@@ -1,40 +1,40 @@
 name: Deploy to github pages
 on:
-  push:
-    branches: [main]
+    push:
+        branches: [main]
 
 jobs:
-  build-and-deploy-to-github-pages:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2.3.1
-        with:
-          submodules: "recursive"
-          lfs: true
+    build-and-deploy-to-github-pages:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v2.3.1
+              with:
+                  submodules: "recursive"
+                  lfs: true
 
-      - name: Install and Build
-        run: |
-          npm install
-          npm run build
+            - name: Install and Build
+              run: |
+                  npm install
+                  npm run build
 
-      - name: Check build size
-        # 1GB = 1073741824 bytes
-        run: |
-          SIZE=$(du -s -B 1 dist/ | cut -f 1)
-          if [[ $SIZE -gt 1073741824 ]]; then echo 'dist folder exceeds limit of 1GB! Aborting'; exit 1; fi
+            - name: Check build size
+              # 1GB = 1073741824 bytes
+              run: |
+                  SIZE=$(du -s -B 1 dist/ | cut -f 1)
+                  if [[ $SIZE -gt 1073741824 ]]; then echo 'dist folder exceeds limit of 1GB! Aborting'; exit 1; fi
 
-      - name: Deploy to Khronos repo
-        continue-on-error: true # If no changes are commited this action fails
-        uses: JamesIves/github-pages-deploy-action@v4.6.3
-        with:
-          branch: main
-          folder: dist/
-          token: ${{ secrets.BUILD_GITHUB_PAGES }}
-          repository-name: KhronosGroup/glTF-Sample-Viewer-Release
-          target-folder: docs
-          clean-exclude: |
-            docs/glxf
-            glxf
-            interactivity
-
+            - name: Deploy to Khronos repo
+              continue-on-error: true # If no changes are commited this action fails
+              uses: JamesIves/github-pages-deploy-action@v4.6.3
+              with:
+                  branch: main
+                  folder: dist/
+                  token: ${{ secrets.BUILD_GITHUB_PAGES }}
+                  repository-name: KhronosGroup/glTF-Sample-Viewer-Release
+                  target-folder: docs
+                  clean-exclude: |
+                      docs/glxf
+                      glxf
+                      interactivity
+                      physics
